### ISSUE TITLE
Uniform Formatting and PEP8 consistency

### ISSUE THREAD

**Issue by adivijaykumar** [gwnrtools/nr-catalog-tools#9]
I saw a lot of `flake8` failures and also noted that there is no uniform formatting across the package. For the latter, I prefer `black`, but I know people have major disagreements there. In any case, thoughts on these?

I can volunteer to put in a PR implementing these (possibly also adding `flake8` checks to CI).

Pinging @prayush on this.

**Comment by prayush** [comment]
Yes, please go ahead @adivijaykumar . I've been using `yapf`, but probably uniformly not across the package.
